# Generated by Django 5.1.1 on 2024-11-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Hot', 'Hot'), ('New', 'New'), ('Normal', 'Normal')], default='Normal', max_length=10),
        ),
    ]
