# Generated by Django 5.1.1 on 2024-12-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cartitem_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'size')},
        ),
    ]
